
name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build docker image
        run: docker build -t docker.io/victor140/vichotel:latest .

      - name: Publish image to docker hub
        run: docker push docker.io/victor140/vichotel:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image from docker hub
        run: docker pull docker.io/victor140/vichotel:latest

      - name: Delete old container
        run: docker rm -f vic-hotel-docker-container

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name vic-hotel-docker-container \
          \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
          -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
          -e AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
          -e AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
          -e MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
          -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
          -e FRONTEND_TESTING_URL=${{ secrets.FRONTEND_TESTING_URL }} \
          -e AWS_FRONTEND_URL=${{ secrets.AWS_FRONTEND_URL }} \
          -e TWILIO_SID=${{ secrets.TWILIO_SID }} \
          -e TWILIO_AUTHTOKEN=${{ secrets.TWILIO_AUTHTOKEN }} \
          -e TWILIO_NUMBER=${{ secrets.TWILIO_NUMBER }} \
          
          docker.io/victor140/vichotel:latest
